"""add_challenge_entries

Revision ID: 098f559e22f4
Revises: a1d5697e3732
Create Date: 2026-06-25 17:49:22.884607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098f559e22f4'
down_revision: Union[str, Sequence[str], None] = 'a1d5697e3732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value >= 0', name='ck_challenge_entries_value_non_negative'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'entry_date', name='uq_challenge_entries_challenge_id_entry_date')
    )
    op.create_index(op.f('ix_challenge_entries_challenge_id'), 'challenge_entries', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_entries_entry_date'), 'challenge_entries', ['entry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_entries_entry_date'), table_name='challenge_entries')
    op.drop_index(op.f('ix_challenge_entries_challenge_id'), table_name='challenge_entries')
    op.drop_table('challenge_entries')
    # ### end Alembic commands ###
