"""add goal color and extend icon

Revision ID: 15ddee2f6f27
Revises: 6e0be017953b
Create Date: 2026-08-15 15:04:51.406146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ddee2f6f27'
down_revision: Union[str, Sequence[str], None] = '6e0be017953b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('color', sa.String(length=10), nullable=True))
    op.alter_column('goals', 'icon',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'icon',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('goals', 'color')
    # ### end Alembic commands ###
