"""create challenges table

Revision ID: 44635f246b44
Revises: 23e8fca5b622
Create Date: 2026-06-23 17:56:54.733322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44635f246b44'
down_revision: Union[str, Sequence[str], None] = '23e8fca5b622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('period', sa.Enum('daily', 'weekly', 'monthly', name='challenge_period'), nullable=False),
    sa.Column('target_type', sa.Enum('min', 'max', 'exact', name='challenge_target_type'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_owner_id'), 'challenges', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenges_owner_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
