"""rename challenges to goals

Revision ID: 6e0be017953b
Revises: 098f559e22f4
Create Date: 2026-08-12 18:42:47.816793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e0be017953b'
down_revision: Union[str, Sequence[str], None] = '098f559e22f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('period', sa.Enum('daily', 'weekly', 'monthly', name='goal_period'), nullable=False),
    sa.Column('target_type', sa.Enum('min', 'max', name='goal_target_type'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('target_value >= 0', name='ck_goals_target_value_non_negative'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_owner_id'), 'goals', ['owner_id'], unique=False)
    op.create_table('goal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value >= 0', name='ck_goal_entries_value_non_negative'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'entry_date', name='uq_goal_entries_goal_id_entry_date')
    )
    op.create_index(op.f('ix_goal_entries_entry_date'), 'goal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_goal_entries_goal_id'), 'goal_entries', ['goal_id'], unique=False)
    op.drop_index(
    op.f('ix_challenge_entries_challenge_id'),
        table_name='challenge_entries',
    )
    op.drop_index(
        op.f('ix_challenge_entries_entry_date'),
        table_name='challenge_entries',
    )
    op.drop_table('challenge_entries')

    op.drop_index(
        op.f('ix_challenges_owner_id'),
        table_name='challenges',
    )
    op.drop_table('challenges')
    sa.Enum(name='challenge_period').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='challenge_target_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('period', postgresql.ENUM('daily', 'weekly', 'monthly', name='challenge_period'), autoincrement=False, nullable=False),
    sa.Column('target_type', postgresql.ENUM('min', 'max', name='challenge_target_type'), autoincrement=False, nullable=False),
    sa.Column('target_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('target_value >= 0::double precision', name=op.f('ck_challenges_target_value_non_negative')),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('challenges_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('challenges_pkey'))
    )
    op.create_index(op.f('ix_challenges_owner_id'), 'challenges', ['owner_id'], unique=False)
    op.create_table('challenge_entries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('value >= 0::double precision', name=op.f('ck_challenge_entries_value_non_negative')),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('challenge_entries_challenge_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('challenge_entries_pkey')),
    sa.UniqueConstraint('challenge_id', 'entry_date', name=op.f('uq_challenge_entries_challenge_id_entry_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_challenge_entries_entry_date'), 'challenge_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_challenge_entries_challenge_id'), 'challenge_entries', ['challenge_id'], unique=False)
    op.drop_index(op.f('ix_goal_entries_goal_id'), table_name='goal_entries')
    op.drop_index(op.f('ix_goal_entries_entry_date'), table_name='goal_entries')
    op.drop_table('goal_entries')
    op.drop_index(op.f('ix_goals_owner_id'), table_name='goals')
    op.drop_table('goals')
    sa.Enum(name='goal_period').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='goal_target_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
