"""add goal position

Revision ID: ad2fd4b0aff5
Revises: 15ddee2f6f27
Create Date: 2026-09-07 18:10:35.904784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad2fd4b0aff5"
down_revision: Union[str, Sequence[str], None] = "15ddee2f6f27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goals",
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.alter_column(
        "goals",
        "position",
        server_default=None,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("goals", "position")
    # ### end Alembic commands ###
